tools update, added 'constants', add 'result_error_field'

diff --git a/ada-link b/ada-link
--- a/ada-link
+++ b/ada-link
@@ -1,39 +1,54 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "ada-link: fatal: $1" 1>&2
+  exit 1
+}
+
 if [ $# -lt 2 ]
 then
-  echo "usage: basename objects ..." 1>&2
+  echo "ada-link: usage: [@dir] basename objects ..." 1>&2
   exit 1
 fi
 
-ADALINK=`head -n 1 conf-adalink`
-if [ $? -ne 0 ]
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
 then
-  echo "fatal: could not read conf-adalink" 1>&2
-  exit 1
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
 fi
-SYSTYPE=`head -n 1 conf-systype`
+
+ADALINK=`head -n 1 "${BASE_DIR}/conf-adalink"`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-systype" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-adalink"
+fi
+SYSTYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-systype"
 fi  
-ADATYPE=`head -n 1 conf-adatype`
+ADATYPE=`head -n 1 "${BASE_DIR}/conf-adatype"`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-adatype" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-adatype"
 fi
 
-ADALDFLAGS="${ADALDFLAGS} `head -n 1 conf-adaldflags 2>/dev/null`"
+ADALDFLAGS="${ADALDFLAGS} `head -n 1 ${BASE_DIR}/conf-adaldflags 2>/dev/null`"
 
 #
 # Read global flag file list, if present.
 #
 
-if [ -f "conf-aldfflist" ]
+if [ -f "${BASE_DIR}/conf-aldfflist" ]
 then
-  for f in `cat "conf-aldfflist"`
+  for f in `cat "${BASE_DIR}/conf-aldfflist"`
   do
     FLAGS=`cat $f 2>/dev/null`
     ADALDFLAGS="${ADALDFLAGS} ${FLAGS}"
